version: "3"
services:
  postgres:
    container_name: postgres_cloud_storage
    image: postgres:latest
    ports:
      - "5433:5433"
    volumes:
      - /data/postgres:/data/postgres
    env_file:
      - docker.env
    networks:
      - postgres
    command: -p 5433

networks:
  postgres:
    driver: bridge